version: '3.8'

version: '3'

networks:
  common:
    external: true

volumes:
    teamcity_data: {}
    docker_data: {}

services:

  teamcity:
    image: jetbrains/teamcity-server:latest
    container_name: teamcity-sa
    volumes:
      - ./volumes/teamcity_server/datadir:/data/teamcity_server/datadir
    restart: unless-stopped
    expose:
      - 8111
    networks:
      - common
    labels:
      org.label-schema.group: "ci"

  teamcity-agent1:
    build:
      context: .
      dockerfile: Dockerfile.agent
    container_name: teamcity-agent-sa1
    volumes:
      - docker_data:/var/lib/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/buildagent/work:/opt/buildagent/work
      - /opt/buildagent/temp:/opt/buildagent/temp
    env_file:
      - env
    restart: unless-stopped
    networks:
      - common
    labels:
      org.label-schema.group: "ci"

  teamcity-agent2:
    build:
      context: .
      dockerfile: Dockerfile.agent
    container_name: teamcity-agent-sa2
    volumes:
      - docker_data:/var/lib/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/buildagent/work:/opt/buildagent/work
      - /opt/buildagent/temp:/opt/buildagent/temp
    env_file:
      - env
    restart: unless-stopped
    networks:
      - common
    labels:
      org.label-schema.group: "ci"

  teamcity-agent3:
    build:
      context: .
      dockerfile: Dockerfile.agent
    container_name: teamcity-agent-sa3
    volumes:
      - docker_data:/var/lib/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/buildagent/work:/opt/buildagent/work
      - /opt/buildagent/temp:/opt/buildagent/temp
    env_file:
      - env
    restart: unless-stopped
    networks:
      - common
    labels:
      org.label-schema.group: "ci"

  teamcity-agent4:
    build:
      context: .
      dockerfile: Dockerfile.agent
    container_name: teamcity-agent-sa4
    volumes:
      - docker_data:/var/lib/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/buildagent/work:/opt/buildagent/work
      - /opt/buildagent/temp:/opt/buildagent/temp
    env_file:
      - env
    restart: unless-stopped
    networks:
      - common
    labels:
      org.label-schema.group: "ci"
