version: '3.8'

volumes:
    teamcity_data:
    docker_data:

x-agent-env:
  environment: &agent-env
    DOCKER_IN_DOCKER: start
    SERVER_URL: http://teamcity-server:8111

x-agent: &agent
  image: teamcity-agent
  build: 
    dockerfile: agent.Dockerfile
  privileged: true
  restart: unless-stopped
  depends_on:
    - teamcity-server
  labels:
    org.label-schema.group: "ci"

services:
  teamcity-server:
    image: jetbrains/teamcity-server:latest
    container_name: teamcity-server
    volumes:
      - teamcity_data:/data/teamcity_server/datadir
    restart: unless-stopped
    depends_on:
      - postgresql
    ports:
      - 80:8111
    labels:
      org.label-schema.group: "ci"

  agent1:
    <<: *agent
    environment:
      <<: *agent-env
      AGENT_NAME: agent-1

  agent2:
    <<: *agent
    environment:
      <<: *agent-env
      AGENT_NAME: agent-2

  agent3:
    <<: *agent
    environment:
      <<: *agent-env
      AGENT_NAME: agent-3

  postgresql:
    image: postgres:latest
    container_name: postgresql
    shm_size: 1g
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: teamcity
      POSTGRES_PASSWORD: teamcity
      POSTGRES_DB: teamcity
    restart: unless-stopped
    expose:
      - 5432
