version: '3.8'

networks:
  teamcity:
    driver: bridge
#    external: true

volumes:
    teamcity_data: {}
    docker_data: {}

services:

  teamcity:
    image: jetbrains/teamcity-server:latest
    user: "0"
    container_name: teamcity-sa
    volumes:
      - ./volumes/:/data/teamcity_server/datadir
    restart: unless-stopped
    ports:
      - 8111:8111
    networks:
      - teamcity
    labels:
      org.label-schema.group: "ci"

  teamcity-agent1:
    image: jetbrains/teamcity-agent:latest
    container_name: teamcity-agent-sa1
    volumes:
      - docker_data:/var/lib/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - ./buildagent/work:/opt/buildagent/work
      - ./buildagent/temp:/opt/buildagent/temp
    env_file:
      - env
    dns:
      - 8.8.8.8
    restart: unless-stopped
    networks:
      - teamcity
    labels:
      org.label-schema.group: "ci"

  postgresql:
    image: postgres:latest
    container_name: database
    shm_size: 1g
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: teamcity
      POSTGRES_PASSWORD: teamcity
      POSTGRES_DB: teamcity
    restart: unless-stopped
    expose:
      - 5432
    networks:
      - teamcity
